"""store master tables (entities/pairs/logs)

Revision ID: 2aee8f3dbf85
Revises: c34e7b8ea63b
Create Date: 2026-09-04 20:20:28.958454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aee8f3dbf85'
down_revision: Union[str, None] = 'c34e7b8ea63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id_raw', sa.String(length=64), nullable=False),
    sa.Column('name_local', sa.Text(), nullable=False),
    sa.Column('name_norm', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('first_seen_import_id', sa.Integer(), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['store_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id_raw')
    )
    op.create_table('store_merge_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('from_master', sa.Integer(), nullable=False),
    sa.Column('to_master', sa.Integer(), nullable=False),
    sa.Column('basis', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['store_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_a', sa.Integer(), nullable=False),
    sa.Column('entity_b', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('sim', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_a'], ['store_entities.id'], ),
    sa.ForeignKeyConstraint(['entity_b'], ['store_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_a', 'entity_b', name='uq_storepair_ab')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_pairs')
    op.drop_table('store_merge_logs')
    op.drop_table('store_entities')
    # ### end Alembic commands ###
