"""daily_activity 全店每日量表

Revision ID: 361b67d26328
Revises: dbed93315747
Create Date: 2026-09-07 13:47:43.612496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361b67d26328'
down_revision: Union[str, None] = 'dbed93315747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity',
    sa.Column('japan_date', sa.Date(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('submitters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('japan_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_activity')
    # ### end Alembic commands ###
