"""store_pairs AI 字段

Revision ID: aa62fd4cc540
Revises: 2aee8f3dbf85
Create Date: 2026-09-04 20:35:16.529654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa62fd4cc540'
down_revision: Union[str, None] = '2aee8f3dbf85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_pairs', sa.Column('ai_decision', sa.String(length=8), nullable=True))
    op.add_column('store_pairs', sa.Column('ai_confidence', sa.String(length=8), nullable=True))
    op.add_column('store_pairs', sa.Column('ai_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_pairs', 'ai_reason')
    op.drop_column('store_pairs', 'ai_confidence')
    op.drop_column('store_pairs', 'ai_decision')
    # ### end Alembic commands ###
