"""initial tables (spec v0.4 §4)

Revision ID: ac89f3182e16
Revises: 
Create Date: 2026-09-04 18:18:21.127336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac89f3182e16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('month_label', sa.String(length=16), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=True),
    sa.Column('data_start_row', sa.Integer(), nullable=True),
    sa.Column('parsed_sheets', sa.JSON(), nullable=False),
    sa.Column('ignored_sheets', sa.JSON(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('parsed_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_sha256')
    )
    op.create_table('self_report_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('boundary_date', sa.Date(), nullable=False),
    sa.Column('rule_version', sa.String(length=64), nullable=True),
    sa.Column('input_import_ids', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_system_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('japan_date', sa.Date(), nullable=False),
    sa.Column('submitter_code', sa.String(length=32), nullable=True),
    sa.Column('final_stores', sa.Integer(), nullable=False),
    sa.Column('points_1', sa.Integer(), nullable=False),
    sa.Column('points_2', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('submitter_code', sa.String(length=32), nullable=True),
    sa.Column('submitter_name', sa.String(length=64), nullable=False),
    sa.Column('raw_submitted', sa.Integer(), nullable=False),
    sa.Column('visible_blank', sa.Integer(), nullable=False),
    sa.Column('dup_count', sa.Integer(), nullable=False),
    sa.Column('final_valid', sa.Integer(), nullable=False),
    sa.Column('points_1', sa.Integer(), nullable=False),
    sa.Column('points_2', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('settle_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'submitter_code', name='uq_pstat_run_person')
    )
    op.create_table('persons',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('first_seen_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('recon_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('source_import_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.ForeignKeyConstraint(['source_import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_report_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('japan_date', sa.Date(), nullable=False),
    sa.Column('submitter_code', sa.String(length=32), nullable=True),
    sa.Column('submitter_name', sa.String(length=64), nullable=True),
    sa.Column('reported_points', sa.Integer(), nullable=False),
    sa.Column('unresolved', sa.Text(), nullable=True),
    sa.Column('original_row', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['self_report_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settle_amounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('submitter_code', sa.String(length=32), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('full_68_groups', sa.Integer(), nullable=False),
    sa.Column('remainder', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=128), nullable=False),
    sa.Column('excel_row', sa.Integer(), nullable=False),
    sa.Column('store_id_raw', sa.Text(), nullable=False),
    sa.Column('store_name_local_raw', sa.Text(), nullable=False),
    sa.Column('store_name_en_raw', sa.Text(), nullable=False),
    sa.Column('modified_raw', sa.Text(), nullable=False),
    sa.Column('submitter_raw', sa.Text(), nullable=False),
    sa.Column('submitter_code', sa.String(length=32), nullable=True),
    sa.Column('record_id_raw', sa.Text(), nullable=False),
    sa.Column('visible_raw', sa.String(length=8), nullable=True),
    sa.Column('deploy_raw', sa.String(length=8), nullable=True),
    sa.Column('original_row', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['submitter_code'], ['persons.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'sheet_name', 'excel_row', name='uq_raw_import_sheet_row')
    )
    op.create_table('recon_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('japan_date', sa.Date(), nullable=True),
    sa.Column('store_id', sa.Text(), nullable=True),
    sa.Column('submitter_code', sa.String(length=32), nullable=True),
    sa.Column('system_value', sa.Integer(), nullable=True),
    sa.Column('report_value', sa.Integer(), nullable=True),
    sa.Column('diff', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('family', sa.String(length=16), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['recon_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clean_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('raw_record_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Text(), nullable=False),
    sa.Column('store_name', sa.Text(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('japan_date', sa.Date(), nullable=True),
    sa.Column('submitter_code', sa.String(length=32), nullable=True),
    sa.Column('visible', sa.String(length=8), nullable=True),
    sa.Column('deploy', sa.String(length=8), nullable=True),
    sa.Column('bucket', sa.String(length=16), nullable=False),
    sa.Column('dup_of_id', sa.Integer(), nullable=True),
    sa.Column('dup_earliest', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dup_of_id'], ['clean_records.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.ForeignKeyConstraint(['submitter_code'], ['persons.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clean_run_bucket', 'clean_records', ['run_id', 'bucket'], unique=False)
    op.create_index('ix_clean_run_date', 'clean_records', ['run_id', 'japan_date'], unique=False)
    op.create_index('ix_clean_run_dupof', 'clean_records', ['run_id', 'dup_of_id'], unique=False)
    op.create_index('ix_clean_run_modified', 'clean_records', ['run_id', 'modified_at'], unique=False)
    op.create_index('ix_clean_run_person_bucket', 'clean_records', ['run_id', 'submitter_code', 'bucket'], unique=False)
    op.create_index('ix_clean_run_person_date', 'clean_records', ['run_id', 'submitter_code', 'japan_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clean_run_person_date', table_name='clean_records')
    op.drop_index('ix_clean_run_person_bucket', table_name='clean_records')
    op.drop_index('ix_clean_run_modified', table_name='clean_records')
    op.drop_index('ix_clean_run_dupof', table_name='clean_records')
    op.drop_index('ix_clean_run_date', table_name='clean_records')
    op.drop_index('ix_clean_run_bucket', table_name='clean_records')
    op.drop_table('clean_records')
    op.drop_table('recon_results')
    op.drop_table('raw_records')
    op.drop_table('settle_amounts')
    op.drop_table('self_report_rows')
    op.drop_table('recon_tasks')
    op.drop_table('persons')
    op.drop_table('person_stats')
    op.drop_table('daily_system_points')
    op.drop_table('task_runs')
    op.drop_table('self_report_imports')
    op.drop_table('imports')
    op.drop_table('users')
    # ### end Alembic commands ###
