"""store_entities address_local

Revision ID: ba8209f06e68
Revises: 99bbfb3dd81a
Create Date: 2026-09-07 11:53:18.288550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8209f06e68'
down_revision: Union[str, None] = '99bbfb3dd81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_entities', sa.Column('address_local', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_entities', 'address_local')
    # ### end Alembic commands ###
