"""clean_records 回源列 sheet_name/excel_row

Revision ID: c34e7b8ea63b
Revises: b34c609aaf98
Create Date: 2026-09-04 19:36:03.231625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34e7b8ea63b'
down_revision: Union[str, None] = 'b34c609aaf98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clean_records', sa.Column('sheet_name', sa.Text(), nullable=False, server_default=sa.text("('')")))
    op.add_column('clean_records', sa.Column('excel_row', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clean_records', 'excel_row')
    op.drop_column('clean_records', 'sheet_name')
    # ### end Alembic commands ###
