"""daily 累计点/累计金额

Revision ID: d209d71a9b99
Revises: 361b67d26328
Create Date: 2026-09-07 14:04:52.787223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd209d71a9b99'
down_revision: Union[str, None] = '361b67d26328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_system_points', sa.Column('cum_points', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('daily_system_points', sa.Column('cum_amount', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_system_points', 'cum_amount')
    op.drop_column('daily_system_points', 'cum_points')
    # ### end Alembic commands ###
